events { worker_connections 1024; }

http {
    # 故意暴露版本号（真实运维错误）
    server_tokens on;

    server {
        listen 80;
        server_name localhost;

        # 主页
        location / {
            root /usr/share/nginx/html;
            index index.html;
        }

        # nginx stub_status 未授权暴露（CVE 关注点）
        location /nginx_status {
            stub_status on;
            allow all;
        }

        # 目录浏览（信息泄露）
        location /files/ {
            root /var/www;
            autoindex on;
        }
    }
}
